export type Product = { id: string; name: string };
export type ModelCode = { id: string; code: string; description: string; legacy_spares_only?: boolean; owner?: { fileId: string; associationId: string; name: string; relativePath?: string | null } | null };
export type ProductModel = { id: string; product_id: string; model_number: string; name: string; productId?: string; modelNumber?: string; modelName?: string; codes: ModelCode[] };
export type CatalogSummary = { root: string; file_count: number; readable_count?: number | null; unreadable_count?: number | null; files_with_external_references?: number | null; external_reference_count?: number | null };
export type ExplorerItem = { id: string; name: string; type: "directory" | "file"; relative_path: string; relativePath?: string; extension: string; size_bytes?: number | null; sizeBytes?: number | null; modified_at?: string | null; modifiedAt?: string | null; candidate_classification?: string; candidateClassification?: string; mapping_status?: string; mappingStatus?: string; readable?: boolean | null; parse_error?: string | null; read_state?: string; readState?: string; sheet_count?: number | null; sheetCount?: number | null; external_reference_count?: number | null; externalReferenceCount?: number | null; external_link_warning?: boolean; externalLinkWarning?: boolean; content_hash?: string | null; contentHash?: string | null; directoryProductMapping?: { mapping: Record<string, unknown>; product: Product; inherited: boolean } | null; directoryMappingProposals?: Record<string, unknown>[] };
export type PreviewCell = { value: unknown; kind: "value" | "formula" | "warning"; formula?: string | null; warning?: PreviewRowWarning };
export type PreviewRowWarning = { severity: "warning"; label: string; message: string; material: string; issueCodes: string[]; rateLogRows: number[]; rateLogCells: string[]; hiddenFields: string[]; durableIssues?: { id: string; status: string; version: number; sourceRow?: number | null }[] };
export type Preview = { path: string; sheets: string[]; sheet: string; startRow: number; startColumn?: number; totalRows: number; totalColumns?: number; truncatedRows?: boolean; truncatedColumns: boolean; readOnly?: boolean; formulaCount?: number; externalReferenceCount?: number; externalLinkWarning?: boolean; rows: unknown[][]; cells?: PreviewCell[][]; refreshMetadata?: { status: "refreshed_temporary_copy"; checkedAt: string; originalSha256: string; refreshedCopySha256: string; linkedSources: { path: string; sha256: string; modified_at: string }[]; sourceWorkbookUnchanged: boolean; linkedSourcesUnchanged: boolean }; rateWarnings?: { status: "not_applicable" | "clear" | "warnings" | "unavailable"; message?: string | null; checkedAt?: string; rows?: Record<string, PreviewRowWarning>; globalWarnings?: { code: string; sourceCell?: string; sourceRow?: number; message: string }[]; sources?: Record<string, { path: string; sha256: string; modified_at: string; observed_at: string }>; materialColumn?: number | null } };
export type ValidationError = { code: string; message: string; field?: string | null; details?: Record<string, unknown> };
export type AssociationValidation = { valid: boolean; errors: ValidationError[]; warnings: ValidationError[]; proposal?: Record<string, unknown> | null };
export type AssociationState = { schemaAvailable: boolean; writeEnabled: boolean; adapter: string; items: MappedFile[]; message?: string | null };
export type ImportBatch = { id: string; source_file: string; source_hash?: string | null; parser_version: string; started_at: string; completed_at?: string | null; status: string; outcome: string };
export type MappedFile = {
  file: Record<string, unknown>;
  product?: Record<string, unknown> | null;
  model?: Record<string, unknown> | null;
  codes: Record<string, unknown>[];
  association?: Record<string, unknown> | null;
  history: Record<string, unknown>[];
  reviewStatus?: "mapped" | "unmapped" | "conflict";
  issues?: string[];
  conflictCodes?: string[];
  lastObservedAt?: string | null;
  lastObservedChange?: { modifiedAt?: string | null; observedAt?: string | null; sizeBytes?: number | null; source?: string } | null;
  processingBatch?: ImportBatch | null;
  latestObservation?: Record<string, unknown> | null;
  movedTo?: string;
  observationHistory?: Record<string, unknown>[];
  durableIssues?: ReconciliationIssue[];
  directoryProductMapping?: { mapping: Record<string, unknown>; product: Product; inherited: boolean } | null;
};

export type ReconciliationIssue = { id: string; fingerprint: string; issue_type: string; severity: string; message: string; source_file: string; source_row?: number | null; entity_type: string; entity_id?: string | null; costing_file_id?: string | null; source_path: string; source_cell: string; detected_facts: Record<string, unknown>; proposed_resolution: Record<string, unknown>; status: string; assigned_owner?: string | null; first_seen_at: string; last_seen_at: string; version: number; resolution_action: string; resolution_reason: string };
export type DirectoryProductMapping = { id: string; relative_path: string; normalized_path: string; product_id: string; inherit: boolean; status: string; proposer: string; approver?: string | null; reason: string; created_at: string; updated_at: string; version: number };
export type CostingReviewLine = {
  source_row: number;
  status: string;
  identity_key: string[];
  machine_piece_description: unknown;
  material_to_cut: string;
  dimension_mm: unknown;
  dimension_inches: unknown;
  quantity: unknown;
  optional_item_group_1: unknown;
  date: unknown;
  remarks: unknown;
  cr_log: unknown;
  item_line_no: unknown;
  source_cells: Record<string, { cell: string; cached_value: unknown; formula?: string | null }>;
  rate_status: string;
  rate: { per_kg: string | null; basis: string; source: string; source_row: number | null; raw_steel_source_row?: number | null; matching_rate_source_rows?: number[]; date: string | null; safety_margin_per_kg: string | null } | null;
  rate_warning?: Record<string, unknown> | null;
  calculation_status: string;
  current_calculation: Record<string, string> | null;
  refreshed_workbook_cached_values: Record<string, unknown>;
  saved_workbook_cached_values: Record<string, unknown> | null;
  cached_formulae: Record<string, string | null>;
  cached_grand_total_difference: string | null;
};
export type CostingReview = {
  schema_version: string;
  status: string;
  read_only: boolean;
  observed_at: string;
  authority: string;
  snapshot_comparison_basis: string;
  matching_key_fields: string[];
  sources: Record<string, { path: string; sha256: string; size_bytes: number; modified_at: string; observed_at: string }>;
  refresh: { required: boolean; verified: boolean; status?: string; checked_at?: string; original_sha256?: string; refreshed_copy_sha256?: string; linked_sources?: { path: string; sha256: string; modified_at: string }[]; source_workbook_unchanged?: boolean; linked_sources_unchanged?: boolean };
  parameters: Record<string, unknown>;
  summary: {
    active_line_count: number;
    historical_line_count: number;
    blocked_active_line_count: number;
    unclassified_line_count: number;
    active_totals: Record<string, string> | null;
    saved_workbook_summary_cache: Record<string, unknown>;
    refreshed_workbook_summary_cache: Record<string, unknown>;
    historical_cached_contribution: Record<string, string>;
    current_total_vs_saved_summary: string | null;
    summary_comparison: Record<string, unknown>[];
  };
  lines: CostingReviewLine[];
  rate_changes_since_saved_snapshot: Record<string, unknown>[];
  material_list_changes_after_refresh: Record<string, unknown>[];
  semantic_snapshot: { semantic_hash: string; source_hashes: Record<string, string>; content: Record<string, unknown>; observed_at: string };
  semantic_comparison: {
    baseline_exists: boolean;
    previous_snapshot_key?: string | null;
    previous_semantic_hash?: string | null;
    current_semantic_hash: string;
    changes: Record<string, any>[];
    ambiguities: Record<string, any>[];
    change_count: number;
    owner_review_required: boolean;
    reason?: string;
    costing_total?: { previous: unknown; current: unknown; difference: unknown };
  };
  costing_file_id?: string | null;
  accepted_baseline?: { snapshot_key: string; semantic_hash: string; accepted_at: string; accepted_by: string } | null;
  persistence_adapter?: string;
  can_accept?: boolean;
  issues: Record<string, unknown>[];
};
